# -*- coding: utf-8 -*-
"""credentials

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BltQNTlT9HFLJqngXiqMeSKepXJGlGCQ
"""

API_KEY = 'Xq2M8vw91X4k09aeT2GomU4m0'
API_SECRET_KEY = '8LyRJjnstNe54AehSJGmXl4CxO0mIJ3sPNE29eRCqq9LAPrCqJ'
BEARER_TOKEN = 'AAAAAAAAAAAAAAAAAAAAAL0xlAEAAAAAhrpUWiKL19vVYnvz%2F0E3iiIXU%2BI%3DFkx9d4Gdzyku1VI516VXf6HHCXntDZJd9okG5Kqg8UeWN2pNht'
ACCESS_TOKEN = '1611218883993653251-lrWrefXYHWkm73OxjjsDbV2lpAnWZW'
ACCESS_TOKEN_SECRET = 'T9OUf1QTnm603IGzmozDifqI3sBP4SkyJr1cnuFfHLxUo'